pages/urls.py
# pages/urls.py


from django.urls import path

from .views import HomeView, AboutView, ContactView

app_name = 'pages'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

readykitchen/urls.py
# readykitchen/urls.py

"""readykitchen URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('recipes/', include('recipes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
# recipes/urls.py


from django.urls import path

from .views import (
    RecipeListView,
    RecipeDetailView,
    RecipeCreateView,
    RecipeUpdateView,
    RecipeDeleteView,
    recipe_share,
)

app_name = 'recipes'
urlpatterns = [
    path('', RecipeListView.as_view(), name='recipe_list'),
    path('<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('new/', RecipeCreateView.as_view(), name='recipe_new'),
    path('<int:pk>/edit/', RecipeUpdateView.as_view(), name='recipe_edit'),
    path('<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe_delete'),
    path('<int:recipe_id>/share/', recipe_share,
         name='recipe_share'),  # fuction-based view is called
]

recipes/models.py
# recipes/models.py

from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy


class RecipeTag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class RecipeManager(models.Manager):
    pass


class Recipe(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=355)
    ingredients = models.CharField(max_length=355)
    procedure = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = models.ManyToManyField(RecipeTag, blank=True)
    # ingredients = models.ManyToManyField(RecipeIngredient, blank=True)

    objects = RecipeManager()  # Manager

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipes:recipe_detail', args=[str(self.id)])


class RecipeImage(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE,
        related_name='recipeimages',)
    image = models.ImageField(upload_to="recipe-images")
    thumbnail = models.ImageField(upload_to="recipe-thumbnails", null=True)

recipes/forms.py
# recipes/forms.py

from django import forms


# for sharing recipe to someone via email
class EmailPostForm(forms.Form):

    name = forms.CharField(max_length=50)
    email_from = forms.EmailField()
    email_to = forms.EmailField()
    message = forms.CharField(required=False, widget=forms.Textarea)

recipes/views.py
# recipes/views.py

from .forms import EmailPostForm
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    paginate_by = 2
    template_name = 'recipes/recipe_list.html'
    login_url = 'login'  # restrict access to non-registered user


class RecipeDetailView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'
    login_url = 'login'


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = ('title', 'subtitle', 'ingredients', 'procedure', 'tags')
    template_name = 'recipes/recipe_new.html'
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    fields = ('title', 'subtitle', 'ingredients', 'procedure', 'tags')
    template_name = 'recipes/recipe_edit.html'
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = 'recipes/recipe_delete.html'
    success_url = reverse_lazy('recipes:recipe_list')
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


# function-based view for sharing recipe via email
def recipe_share(request, recipe_id):

    # Retrieve recipe by id
    recipe = get_object_or_404(Recipe, id=recipe_id)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)

        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            recipe_url = request.build_absolute_uri(recipe.get_absolute_url())
            subject = '{}({}) recommends you reading "{}"'.format(
                cd['name'],
                cd['email_from'],
                recipe.title
            )
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                recipe.title,
                recipe_url,
                cd['name'],
                cd['message']
            )
            send_mail(subject, message,
                      'admin@readykitchen.com', [cd['email_to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'recipes/recipe_share.html', {'recipe': recipe,
                                                         'form': form,
                                                         'sent': sent})

recipes/templates/recipes/pagination.html
{% comment %} recipes/templates/recipes/pagination.html {% endcomment %}

<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page.previous_page_number }}">&laquo; Previous</a>
        {% endif %}
        <span class="current">
            [ Page {{ page.number }} of {{ page.paginator.num_pages }} ]
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next &raquo;</a>
            <a href="?page={{ page.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
</div>  

recipes/templates/recipes/recipe_delete.html
<!-- recipes/templates/recipes/recipe_delete.html  -->

{% extends 'base.html' %}

{% block title %} Recipe: {{ object.title }} {% endblock title %}

{% block content %}
<h2>Delete</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete <em>"{{ recipe.title }}"</em>?</p>
  <button class="btn btn-danger" type="submit">Confirm</button>
  <button class="btn btn-secondary" type="submit">
    <a style="text-decoration:none;" class="text-white" href="{% url 'recipes:recipe_detail' recipe.pk %}">Cancel</a>
  </button>
</form>
{% endblock content %}

recipes/templates/recipes/recipe_detail.html
<!-- recipes/templates/recipes/recipe_detail.html  -->

{% extends 'base.html' %}

{% block title %} Recipe: {{ object.title }} {% endblock title %}

{% block content %}
    <div class="article-entry">
        <h2>{{ object.title }}</h2>
        <p class="text-muted">by {{ object.author }} | {{ object.date }}</p>
        <p>
            {% comment %} if related name is not defined in 'RecipeImage' model{% endcomment %}
            {% comment %} {% for image in object.recipeimage_set.all %}  {% endcomment %}
            {% for image in object.recipeimages.all %}
                <img src="{{ image.thumbnail.url }}" alt="cover"/>
            {% endfor %}
        </p>
        <p class="text-justify">{{ object.subtitle }}</p>
        <p class="text-justify"> Ingredients for this recipe: {{ object.ingredients }}.</p>
        <p class="text-justify">{{ object.procedure }}</p>
        <p class="text-justify">{{ object.end }}</p>
    </div>
    <div class="text-muted">
        {% if request.user == object.author %}
            <a class="btn btn-secondary" href="{% url 'recipes:recipe_edit' object.pk %}">Edit</a> 
            <a class="btn btn-secondary" href="{% url 'recipes:recipe_delete' object.pk %}">Delete</a>
        {% endif %} 
        <a class ="btn btn-secondary" href="{% url "recipes:recipe_share" object.pk %}">Share</a>       
    </div><br \>
    
    {% comment %} showing list of comments {% endcomment %}
    {% if recipe.comments.all %}
        <div class="card-footer text-muted">
            {% for comment in recipe.comments.all %}
                <p class="">
                    Comment by
                    <span class="font-weight-bold">
                        {{ comment.author }} &middot;
                    </span>
                    {{ comment.message }}
                </p>
                {% if not forloop.last %}<hr />{% endif %}
            {% endfor %} 
        </div>
    {% endif %}
{% endblock content %}

recipes/templates/recipes/recipe_edit.html
<!-- recipes/templates/recipes/recipe_edit.html  -->

{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Recipe: {{ object.title }} {% endblock title %}

{% block content %}
  <h2>Edit</h2>
  <form method="post">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form|crispy }}
        <button class="btn btn-info" type="submit">Update</button>
        <button class="btn btn-secondary" type="submit">
        <a style="text-decoration:none;" class="text-white" href="{% url 'recipes:recipe_detail' recipe.pk %}">Cancel</a>
        </button>
  </form>
{% endblock content %}

recipes/templates/recipes/recipe_list.html
<!-- recipes/templates/recipes/article_list.html   -->


{% extends 'base.html' %}

{% block title %} Recipes {% endblock title %}

{% block content %}
  {% for recipe in object_list %}
    <div class="card">
      <div class="card-header">
        <span class="font-weight-bold">
          {{ recipe.title }}
        </span> &middot;
        <span class="text-muted">
          by {{ recipe.author }} | {{ recipe.date }}
        </span>
      </div>
      <div class="card-body text-justify">
        <p>{{ recipe.subtitle }}</p><hr />
        {% if request.user == recipe.author %}
          <a href="{% url 'recipes:recipe_edit' recipe.pk %}">Edit</a> |
          <a href="{% url 'recipes:recipe_delete' recipe.pk %}">Delete</a> |
        {% endif %}
        <a href="{% url 'recipes:recipe_detail' recipe.pk %}">View Details</a> 
      </div>
      <div class="card-footer text-muted">
        <span>
            Total number of comments posted on this recipe:
            <span class="font-weight-bold">{{ recipe.comments.all.count }}</span>
        </span>
      </div>
    </div>
    <br />
  {% endfor %}
  {% include "recipes/pagination.html" with page=page_obj %}
{% endblock content %}

recipes/templates/recipes/recipe_new.html
<!-- recipes/templates/recipes/recipe_new.html  -->

{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} New Recipe {% endblock title %}

{% block content %}
  <h2>New Recipe</h2>
  <form method="post">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Save</button>
  </form>
{% endblock content %}

recipes/templates/recipes/recipe_share.html
<!-- recipes/templates/recipes/recipe_share.html -->

{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Share a recipe{% endblock %}
{% block content %}
    {% if sent %}
        <h2>E-mail successfully sent</h2>
        <p>
            "{{ recipe.title }}" was successfully sent to "{{ form.cleaned_data.email_to }}".
        </p>
    {% else %}
        <h2>Share "{{ recipe.title }}" by e-mail</h2>
        <form action="." method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <button class="btn btn-success" type="submit">Send e-mail</button>
        </form>
    {% endif %}
{% endblock %}