pages/urls.py
# pages/urls.py


from django.urls import path

from .views import HomeView, AboutView, ContactView

app_name = 'pages'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

readykitchen/urls.py
# readykitchen/urls.py

"""readykitchen URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('recipes/', include('recipes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
# recipes/urls.py


from django.urls import path

from .views import (
    RecipeListView,
    RecipeDetailView,
    RecipeCreateView,
    RecipeUpdateView,
    RecipeDeleteView,
    recipe_share,
)

app_name = 'recipes'
urlpatterns = [
    path('', RecipeListView.as_view(), name='recipe_list'),
    path('<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('new/', RecipeCreateView.as_view(), name='recipe_new'),
    path('<int:pk>/edit/', RecipeUpdateView.as_view(), name='recipe_edit'),
    path('<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe_delete'),
    path('<int:recipe_id>/share/', recipe_share,
         name='recipe_share'),  # fuction-based view is called
]

users/urls.py
# users/urls.py

from django.urls import path

from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup')
]

pages/forms.py
# pages/forms.py

from django import forms
from django.core.mail import send_mail

# import logging

# logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        # logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "ReadyKitcheN contact message",             # message subject
            message,                                    # message body
            "contact@readykitchen.domain",              # message 'from'
            ["customerservice@readykitchen.domain"],    # message 'to'
            fail_silently=False,
        )

pages/templates/pages/about.html
<!-- pages/templates/pages/about.html  -->

{% extends "base.html" %}

{% block title %}About{% endblock title %}

{% block content %}
    <h2>About ReadyKitcheN</h2><hr />
    <p>ReadyKitcheN is a kind of online kitchen where you will find all sorts of recipe for cokking</p>
    <p>However, this is closed kichen, that means, you have to be a member to access it</p>
    <p>
        But you are free to open register here abolutely for free. 
        Wow!!! That's amazing Just go to the sign up page. 
        <br>It only takes a minute to be a member on this online kitchen.
    </p>
{% endblock content %}

pages/templates/pages/contact.html
<!-- main/templates/contact_form.html  -->

{% extends "base.html" %}
{% block content %}
    <h2>Contact us</h2><hr />
    <p>Please fill the form below to contact us</p>
    <!-- <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit
        </button>
    </form> -->
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name" name="name"
                placeholder="Your name" value="{{ form.name.value|default:"" }}">
            {% if form.name.errors %}
                <div class="invalid-feedback">
                    {{ form.name.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}
            <textarea class="form-control {% if form.message.errors %}is-invalid{% endif %}" id="id_message" name="message"
                rows="3">
                {{ form.message.value|default:""}}
            </textarea>
            {% if form.message.errors %}
                <div class="invalid-feedback">
                    {{ form.message.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

pages/templates/pages/home.html
<!-- templates/home.html  -->

{% extends 'base.html' %}

{% block title %} Home {% endblock title %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">ReadyKitchen App</h1>
        <p class="lead text-justify">
            Welcome to <em>ReadyKitchen</em> APP.
            You will find all kinds of recipe here for free.
            This is a members only app. If you are not a member then please register for free.
            A registered user can view all recipes, post recipe, and write comments on the recipes.
            Only the author of the recipe can edit or delete it, and others only can read and comment on it.
        </p>
        <p class="lead">
            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg" role="button" href="{% url 'recipes:recipe_list' %}">
                View All Recipes
                </a>
            {% else %}
                <a class="btn btn-secondary btn-md" role="button" href="{% url 'login' %}">
                Log in to access
                </a>
                <a class="btn btn-primary btn-md" role="button" href="{% url 'users:signup' %}">
                New? Register here
                </a>
            {% endif %}
        </p>
    </div>
{% endblock content %}